name: shengbentong
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  dio: ^5.11.0
  flutter:
    sdk: flutter
  markdown_widget: ^2.3.2+8
  path: ^1.9.1
  shared_preferences: ^2.5.5
  sqflite: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.2+1

flutter:
  uses-material-design: true
